version: '3.8'

services:
 web:
  build: ./web
  ports:
  - 5005:5005
  volumes:
  - ./:/app
  environment:
    FLASK_ENV: development
 node1:
  build: ./node1
  ports:
  - 5001:5001
  volumes:
  - ./:/app
  environment:
    FLASK_ENV: development
 node2:
  build: ./node2
  ports:
  - 5002:5002
  volumes:
  - ./:/app
  environment:
    FLASK_ENV: development
 node3:
  build: ./node3
  ports:
  - 5003:5003
  volumes:
  - ./:/app
  environment:
    FLASK_ENV: development
 node4:
  build: ./node4
  ports:
  - 5004:5004
  volumes:
  - ./:/app
  environment:
    FLASK_ENV: development
 pub:
  build: ./pub
  ports:
  - 5000:5000
  volumes:
  - ./:/app
  environment:
    FLASK_ENV: development
 webdb:
  image: mysql
  ports:
  - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: pass
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql
 node1db:
  image: mysql
  ports:
  - 3307:3306
  environment:
    MYSQL_ROOT_PASSWORD: pass
  volumes:
  - node1mysql:/var/lib/mysql
  - node1mysql_config:/etc/mysql
 node2db:
  image: mysql
  ports:
  - 3308:3306
  environment:
    MYSQL_ROOT_PASSWORD: pass
  volumes:
  - node2mysql:/var/lib/mysql
  - node2mysql_config:/etc/mysql
 node3db:
  image: mysql
  ports:
  - 3309:3306
  environment:
    MYSQL_ROOT_PASSWORD: pass
  volumes:
  - node3mysql:/var/lib/mysql
  - node3mysql_config:/etc/mysql
 node4db:
  image: mysql
  ports:
  - 3310:3306
  environment:
    MYSQL_ROOT_PASSWORD: pass
  volumes:
  - node4mysql:/var/lib/mysql
  - node4mysql_config:/etc/mysql
  

volumes:
  mysql:
  mysql_config:
  node1mysql:
  node1mysql_config:
  node2mysql:
  node2mysql_config:
  node3mysql:
  node3mysql_config:
  node4mysql:
  node4mysql_config:
networks:
  default:
    external: true
    name: msgnet