version: '3.8'

services:
 web:
  build:
   context: .
  ports:
  - 5000:5000
  volumes:
  - ./:/app
  environment:
    FLASK_ENV: development
 msgdb:
  image: mysql
  ports:
  - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: pass
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config:
networks:
  default:
    external: true
    name: msgnet